name: ScottE's blog - sail2software
url: http://sail2software.com
description: Random things - everything from sailing to software

comments: true
permalink: /:year/:month/:title.html
paginate: 10
highlighter: pygments
markdown: redcarpet

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
